//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.24 at 04:35:23 ÏÂÎç CST 
//


package com.sun.java.xml.ns.j2ee;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for web-appType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="web-appType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;group ref="{http://java.sun.com/xml/ns/j2ee}descriptionGroup"/>
 *         &lt;element name="distributable" type="{http://java.sun.com/xml/ns/j2ee}emptyType"/>
 *         &lt;element name="context-param" type="{http://java.sun.com/xml/ns/j2ee}param-valueType"/>
 *         &lt;element name="filter" type="{http://java.sun.com/xml/ns/j2ee}filterType"/>
 *         &lt;element name="filter-mapping" type="{http://java.sun.com/xml/ns/j2ee}filter-mappingType"/>
 *         &lt;element name="listener" type="{http://java.sun.com/xml/ns/j2ee}listenerType"/>
 *         &lt;element name="servlet" type="{http://java.sun.com/xml/ns/j2ee}servletType"/>
 *         &lt;element name="servlet-mapping" type="{http://java.sun.com/xml/ns/j2ee}servlet-mappingType"/>
 *         &lt;element name="session-config" type="{http://java.sun.com/xml/ns/j2ee}session-configType"/>
 *         &lt;element name="mime-mapping" type="{http://java.sun.com/xml/ns/j2ee}mime-mappingType"/>
 *         &lt;element name="welcome-file-list" type="{http://java.sun.com/xml/ns/j2ee}welcome-file-listType"/>
 *         &lt;element name="error-page" type="{http://java.sun.com/xml/ns/j2ee}error-pageType"/>
 *         &lt;element name="jsp-config" type="{http://java.sun.com/xml/ns/j2ee}jsp-configType"/>
 *         &lt;element name="security-constraint" type="{http://java.sun.com/xml/ns/j2ee}security-constraintType"/>
 *         &lt;element name="login-config" type="{http://java.sun.com/xml/ns/j2ee}login-configType"/>
 *         &lt;element name="security-role" type="{http://java.sun.com/xml/ns/j2ee}security-roleType"/>
 *         &lt;group ref="{http://java.sun.com/xml/ns/j2ee}jndiEnvironmentRefsGroup"/>
 *         &lt;element name="message-destination" type="{http://java.sun.com/xml/ns/j2ee}message-destinationType"/>
 *         &lt;element name="locale-encoding-mapping-list" type="{http://java.sun.com/xml/ns/j2ee}locale-encoding-mapping-listType"/>
 *       &lt;/choice>
 *       &lt;attribute name="version" use="required" type="{http://java.sun.com/xml/ns/j2ee}web-app-versionType" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "web-appType", namespace = "http://java.sun.com/xml/ns/j2ee", propOrder = {
    "descriptionAndDisplayNameAndIcon"
})
public class WebAppType {

    @XmlElements({
        @XmlElement(name = "error-page", namespace = "http://java.sun.com/xml/ns/j2ee", type = ErrorPageType.class),
        @XmlElement(name = "message-destination-ref", namespace = "http://java.sun.com/xml/ns/j2ee", type = MessageDestinationRefType.class),
        @XmlElement(name = "session-config", namespace = "http://java.sun.com/xml/ns/j2ee", type = SessionConfigType.class),
        @XmlElement(name = "env-entry", namespace = "http://java.sun.com/xml/ns/j2ee", type = EnvEntryType.class),
        @XmlElement(name = "mime-mapping", namespace = "http://java.sun.com/xml/ns/j2ee", type = MimeMappingType.class),
        @XmlElement(name = "jsp-config", namespace = "http://java.sun.com/xml/ns/j2ee", type = JspConfigType.class),
        @XmlElement(name = "resource-env-ref", namespace = "http://java.sun.com/xml/ns/j2ee", type = ResourceEnvRefType.class),
        @XmlElement(name = "login-config", namespace = "http://java.sun.com/xml/ns/j2ee", type = LoginConfigType.class),
        @XmlElement(name = "icon", namespace = "http://java.sun.com/xml/ns/j2ee", type = IconType.class),
        @XmlElement(name = "filter", namespace = "http://java.sun.com/xml/ns/j2ee", type = FilterType.class),
        @XmlElement(name = "filter-mapping", namespace = "http://java.sun.com/xml/ns/j2ee", type = FilterMappingType.class),
        @XmlElement(name = "security-constraint", namespace = "http://java.sun.com/xml/ns/j2ee", type = SecurityConstraintType.class),
        @XmlElement(name = "servlet-mapping", namespace = "http://java.sun.com/xml/ns/j2ee", type = ServletMappingType.class),
        @XmlElement(name = "context-param", namespace = "http://java.sun.com/xml/ns/j2ee", type = ParamValueType.class),
        @XmlElement(name = "description", namespace = "http://java.sun.com/xml/ns/j2ee", type = DescriptionType.class),
        @XmlElement(name = "ejb-ref", namespace = "http://java.sun.com/xml/ns/j2ee", type = EjbRefType.class),
        @XmlElement(name = "service-ref", namespace = "http://java.sun.com/xml/ns/j2ee", type = ServiceRefType.class),
        @XmlElement(name = "ejb-local-ref", namespace = "http://java.sun.com/xml/ns/j2ee", type = EjbLocalRefType.class),
        @XmlElement(name = "security-role", namespace = "http://java.sun.com/xml/ns/j2ee", type = SecurityRoleType.class),
        @XmlElement(name = "servlet", namespace = "http://java.sun.com/xml/ns/j2ee", type = ServletType.class),
        @XmlElement(name = "welcome-file-list", namespace = "http://java.sun.com/xml/ns/j2ee", type = WelcomeFileListType.class),
        @XmlElement(name = "listener", namespace = "http://java.sun.com/xml/ns/j2ee", type = ListenerType.class),
        @XmlElement(name = "display-name", namespace = "http://java.sun.com/xml/ns/j2ee", type = DisplayNameType.class),
        @XmlElement(name = "resource-ref", namespace = "http://java.sun.com/xml/ns/j2ee", type = ResourceRefType.class),
        @XmlElement(name = "distributable", namespace = "http://java.sun.com/xml/ns/j2ee", type = EmptyType.class),
        @XmlElement(name = "locale-encoding-mapping-list", namespace = "http://java.sun.com/xml/ns/j2ee", type = LocaleEncodingMappingListType.class),
        @XmlElement(name = "message-destination", namespace = "http://java.sun.com/xml/ns/j2ee", type = MessageDestinationType.class)
    })
    protected List<Object> descriptionAndDisplayNameAndIcon;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected java.lang.String version;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected java.lang.String id;

    /**
     * Gets the value of the descriptionAndDisplayNameAndIcon property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the descriptionAndDisplayNameAndIcon property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescriptionAndDisplayNameAndIcon().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ErrorPageType }
     * {@link MessageDestinationRefType }
     * {@link SessionConfigType }
     * {@link EnvEntryType }
     * {@link MimeMappingType }
     * {@link JspConfigType }
     * {@link ResourceEnvRefType }
     * {@link LoginConfigType }
     * {@link IconType }
     * {@link FilterType }
     * {@link FilterMappingType }
     * {@link SecurityConstraintType }
     * {@link ServletMappingType }
     * {@link ParamValueType }
     * {@link DescriptionType }
     * {@link EjbRefType }
     * {@link ServiceRefType }
     * {@link EjbLocalRefType }
     * {@link SecurityRoleType }
     * {@link ServletType }
     * {@link WelcomeFileListType }
     * {@link ListenerType }
     * {@link DisplayNameType }
     * {@link ResourceRefType }
     * {@link EmptyType }
     * {@link LocaleEncodingMappingListType }
     * {@link MessageDestinationType }
     * 
     * 
     */
    public List<Object> getDescriptionAndDisplayNameAndIcon() {
        if (descriptionAndDisplayNameAndIcon == null) {
            descriptionAndDisplayNameAndIcon = new ArrayList<Object>();
        }
        return this.descriptionAndDisplayNameAndIcon;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setVersion(java.lang.String value) {
        this.version = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

}
